### ISSUE TITLE
code snnipets

### ISSUE THREAD

**Issue by jaan143** [learnbyexample/learnbyexample.github.io#1]
hello
i am trying to generate epub from markdown using your epub.css
and i read your whole article but i cannot success to code snnipets 
it is showing as normal text. 
can you please help me to solve my issue ?

**Comment by learnbyexample** [comment]
Not sure if I will be able to help troubleshoot your issue. https://tex.stackexchange.com/ would probably be better suited.

In any case, it would help if you can show the input file and exact command you used (or attach them), along with screenshot of output you get (because your epub reader might have issues too).

Also, did you try the samples I mention in the blog post? All the files are present in the https://github.com/learnbyexample/learnbyexample.github.io/tree/master/files/pandoc_pdf folder and if you use `./md2epub.sh sample_5.md chk.epub` it should give you similar output as `sample_5.epub` present in that folder.

**Comment by jaan143** [comment]
well i figured out the issue.
now i just want help but not related to your project.
i am scraping website text where i have table of content list also in .md file but i want to detect that chapters and add # before every chapter name. right know i have to copy chapter name from table of content list and find and then adding # . but with this i have to do manual one by one which is taking too much time. i want to any software or script where i can add chapter name list and it will find that lines from while .md file and add # before every line of chapter name.

**Comment by learnbyexample** [comment]
I'd suggest to ask such questions on forums like https://www.reddit.com/r/learnprogramming/ and https://stackoverflow.com/ (be sure to add some sample input, code, etc).
